### ISSUE TITLE
ISBNから商品の小売価格取得できない問題

### ISSUE THREAD

**Issue by a-r-g-v** [9cumber/server#20]
現時点では Amazon Advertising API を使用して ISBN13 から 書籍情報を取得しているが，この方法では小売価格を取得することができない（新品で販売されている場合，新品の商品価格を取得することができる．）

Google Books API や 楽天 API 等 などからも，商品の小売価格を取得することは難しい．

商品の小売価格の取得を頑張るか，他の方法を探すかしたい

**Comment by RomTin** [comment]
利用可能なAPIのうちで正確にメーカー希望小売価格を返却してくれるAPIは存在しない。
最終手段として、書籍のバーコードスキャン時にOCRで定価を認識し登録する方法がある。（なるべく回避する）

**Comment by RomTin** [comment]
売店で書籍の小売価格情報とISBN番号が紐付けられたデータを保管している場合にはそれを利用する。

**Comment by a-r-g-v** [comment]
- 暫定では 下記の方法で得た Amazon の Price を入れておく
  -  yoavaviram/python-amazon-simple-product-api の api.AmazonProduct.list_price で得た currencyが JPY のもの
  - もしくは，None
