### ISSUE TITLE
admin-user, student-userを判別するためのdecoratorの実装

### ISSUE THREAD

**Issue by RomTin** [9cumber/server#27]
admin専用ページ、student専用ページへのアクセス制限を設けるためのdecoratorを実装する
### admin_required
1. ユーザーが非ログイン時にログイン用画面にリダイレクトする（login_requiredと同じ挙動）
```python
# flask-loginのlogin_required decoratorの実装
from functools import wraps
from flask import g, request, redirect, url_for

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if g.user is None:
            return redirect(url_for('login', next=request.url))
        return f(*args, **kwargs)
    return decorated_function
```
2. ログインユーザーが持つ`is_admin`フラグが1出ない時に403 Forbiddenの例外を投げる。

### student_reqiured
1. ユーザーが非ログイン時にログイン用画面にリダイレクトする（login_requiredと同じ挙動）
2. ログインユーザーが持つ`is_admin` フラグが0でないときに403 Forbiddenの例外を投げる。

**Comment by a-r-g-v** [comment]
ユーザがログインしていない場合は，どういう挙動をすれば良いですか？

**Comment by RomTin** [comment]
flask-loginのログイン判別用decoratorと併用する予定なのでログインしていない場合は想定していないんですけど、一応定義したほうがいいかな

**Comment by a-r-g-v** [comment]
しといてください．
また，例外の種類に指定があれば教えてください．なければ，新規に定義します．

**Comment by RomTin** [comment]
どうでしょう

**Comment by a-r-g-v** [comment]
どう？とは…

**Comment by RomTin** [comment]
これ定義は十分かどうかって話

**Comment by a-r-g-v** [comment]
確認しました，大丈夫だと思います！

**Comment by a-r-g-v** [comment]
student_required
> ログインユーザーが持つis_admin フラグが0でないときに403 Forbiddenの例外を投げる。
これ，必要ですか？（studentしか見れないページ⊆adminしか見れないページ，というわけではない？）

**Comment by RomTin** [comment]
adminには買う側のユーザー（=student）のページにアクセスできる必要が無いと思ったんですけどどうですか
admin側から取り置きとかできてしまうことになりかねないのでいっそ制限した方がいいかと思いました
studentが見れるページとadminが見れるページは一部共通ですが包含関係には無いという認識です

adminがstudent_requiredなページ全てを見ることができても問題無さそうであればstudent_requiredの実装は省略しても良いかもしれません

**Comment by a-r-g-v** [comment]
@RomTin 
例えば，テスト時にadminが取り置きを試すようなユースケースも考えられなくはないかな，と思うので，adminが取り置きをできても問題ないのでは？という風に考えますが，どう思いますか？拡張して，studentしかアクセスできないページはない，という風にしたいと思うのですが，どう思いますか？

**Comment by RomTin** [comment]
studentがアプリ上で使用できる機能によりそうなんですけど、adminが使用してはいけない機能があるとしたらstudent_requiredの実装は必要そうですよね
問題無さそうですかね

**Comment by a-r-g-v** [comment]
はい，studentが使用できてadminが使用できない機能は存在させない，という方針で行きたい．

**Comment by RomTin** [comment]
OKです
